import Head from "next/head";
import Link from "next/link";

const lista = [
  ["/estatica01", "Renderização Estática 1"],
  ["/estatica02", "Renderização Estática 2"],
  ["/estatica03", "Renderização Estática 3"],
  ["/estatica04", "Renderização Estática 4"],
  ["/alunos/3", "Renderização Estática 5 - Aluno pré renderizado"],
  ["/alunos/30", "Renderização Estática 6 - Aluno não pré renderizado"],
  ["/dinamica01", "Renderização Dinâmica 1"],
  ["/dinamica02", "Renderização Dinâmica 2"],
];

export default function Index() {
  return (
    <div>
      <Head>
        <title>05-renderizacoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ol
          style={{
            fontSize: "20px",
            lineHeight: "30px",
            margin: "20px 0 0 40px",
            listStyle: "number",
          }}
        >
          {lista.map(([url, titulo], i) => (
            <li key={i}>
              <Link href={url}>{titulo}</Link>
            </li>
          ))}
        </ol>
      </main>
    </div>
  );
}
